// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"

	resource "k8s.io/apimachinery/pkg/api/resource"

	v1 "github.com/freshworks/redis-operator/api/redisfailover/v1"
)

// RedisFailoverCheck is an autogenerated mock type for the RedisFailoverCheck type
type RedisFailoverCheck struct {
	mock.Mock
}

// CheckAllSlavesFromMaster provides a mock function with given fields: master, rFailover
func (_m *RedisFailoverCheck) CheckAllSlavesFromMaster(master string, rFailover *v1.RedisFailover) error {
	ret := _m.Called(master, rFailover)

	if len(ret) == 0 {
		panic("no return value specified for CheckAllSlavesFromMaster")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *v1.RedisFailover) error); ok {
		r0 = rf(master, rFailover)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckIfMasterLocalhost provides a mock function with given fields: rFailover
func (_m *RedisFailoverCheck) CheckIfMasterLocalhost(rFailover *v1.RedisFailover) (bool, error) {
	ret := _m.Called(rFailover)

	if len(ret) == 0 {
		panic("no return value specified for CheckIfMasterLocalhost")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover) (bool, error)); ok {
		return rf(rFailover)
	}
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover) bool); ok {
		r0 = rf(rFailover)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(*v1.RedisFailover) error); ok {
		r1 = rf(rFailover)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckRedisNumber provides a mock function with given fields: rFailover
func (_m *RedisFailoverCheck) CheckRedisNumber(rFailover *v1.RedisFailover) error {
	ret := _m.Called(rFailover)

	if len(ret) == 0 {
		panic("no return value specified for CheckRedisNumber")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover) error); ok {
		r0 = rf(rFailover)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckRedisSlavesReady provides a mock function with given fields: slaveIP, rFailover
func (_m *RedisFailoverCheck) CheckRedisSlavesReady(slaveIP string, rFailover *v1.RedisFailover) (bool, error) {
	ret := _m.Called(slaveIP, rFailover)

	if len(ret) == 0 {
		panic("no return value specified for CheckRedisSlavesReady")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *v1.RedisFailover) (bool, error)); ok {
		return rf(slaveIP, rFailover)
	}
	if rf, ok := ret.Get(0).(func(string, *v1.RedisFailover) bool); ok {
		r0 = rf(slaveIP, rFailover)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, *v1.RedisFailover) error); ok {
		r1 = rf(slaveIP, rFailover)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRedisPodMemoryUsage provides a mock function with given fields: redisIP, rFailover
func (_m *RedisFailoverCheck) GetRedisPodMemoryUsage(redisIP string, rFailover *v1.RedisFailover) (int64, error) {
	ret := _m.Called(redisIP, rFailover)

	if len(ret) == 0 {
		panic("no return value specified for GetRedisPodMemoryUsage")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *v1.RedisFailover) (int64, error)); ok {
		return rf(redisIP, rFailover)
	}
	if rf, ok := ret.Get(0).(func(string, *v1.RedisFailover) int64); ok {
		r0 = rf(redisIP, rFailover)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string, *v1.RedisFailover) error); ok {
		r1 = rf(redisIP, rFailover)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckSentinelMonitor provides a mock function with given fields: sentinel, masterName, monitor
func (_m *RedisFailoverCheck) CheckSentinelMonitor(sentinel string, masterName string, monitor ...string) error {
	_va := make([]interface{}, len(monitor))
	for _i := range monitor {
		_va[_i] = monitor[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, sentinel, masterName)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CheckSentinelMonitor")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, ...string) error); ok {
		r0 = rf(sentinel, masterName, monitor...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckSentinelNumber provides a mock function with given fields: rFailover
func (_m *RedisFailoverCheck) CheckSentinelNumber(rFailover *v1.RedisFailover) error {
	ret := _m.Called(rFailover)

	if len(ret) == 0 {
		panic("no return value specified for CheckSentinelNumber")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover) error); ok {
		r0 = rf(rFailover)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckSentinelNumberInMemory provides a mock function with given fields: sentinel, rFailover
func (_m *RedisFailoverCheck) CheckSentinelNumberInMemory(sentinel string, rFailover *v1.RedisFailover) error {
	ret := _m.Called(sentinel, rFailover)

	if len(ret) == 0 {
		panic("no return value specified for CheckSentinelNumberInMemory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *v1.RedisFailover) error); ok {
		r0 = rf(sentinel, rFailover)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckSentinelQuorum provides a mock function with given fields: rFailover
func (_m *RedisFailoverCheck) CheckSentinelQuorum(rFailover *v1.RedisFailover) (int, error) {
	ret := _m.Called(rFailover)

	if len(ret) == 0 {
		panic("no return value specified for CheckSentinelQuorum")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover) (int, error)); ok {
		return rf(rFailover)
	}
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover) int); ok {
		r0 = rf(rFailover)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(*v1.RedisFailover) error); ok {
		r1 = rf(rFailover)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckSentinelSlavesNumberInMemory provides a mock function with given fields: sentinel, rFailover
func (_m *RedisFailoverCheck) CheckSentinelSlavesNumberInMemory(sentinel string, rFailover *v1.RedisFailover) error {
	ret := _m.Called(sentinel, rFailover)

	if len(ret) == 0 {
		panic("no return value specified for CheckSentinelSlavesNumberInMemory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *v1.RedisFailover) error); ok {
		r0 = rf(sentinel, rFailover)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMasterIP provides a mock function with given fields: rFailover
func (_m *RedisFailoverCheck) GetMasterIP(rFailover *v1.RedisFailover) (string, error) {
	ret := _m.Called(rFailover)

	if len(ret) == 0 {
		panic("no return value specified for GetMasterIP")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover) (string, error)); ok {
		return rf(rFailover)
	}
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover) string); ok {
		r0 = rf(rFailover)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*v1.RedisFailover) error); ok {
		r1 = rf(rFailover)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMaxRedisPodTime provides a mock function with given fields: rFailover
func (_m *RedisFailoverCheck) ComputeRequiredHeadroom(rFailover *v1.RedisFailover, nodeName string, masterPodName string) (resource.Quantity, resource.Quantity, error) {
	ret := _m.Called(rFailover, nodeName, masterPodName)

	if len(ret) == 0 {
		panic("no return value specified for ComputeRequiredHeadroom")
	}

	var r0 resource.Quantity
	var r1 resource.Quantity
	var r2 error
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover, string, string) (resource.Quantity, resource.Quantity, error)); ok {
		return rf(rFailover, nodeName, masterPodName)
	}
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover, string, string) resource.Quantity); ok {
		r0 = rf(rFailover, nodeName, masterPodName)
	} else {
		r0 = ret.Get(0).(resource.Quantity)
	}

	if rf, ok := ret.Get(1).(func(*v1.RedisFailover, string, string) resource.Quantity); ok {
		r1 = rf(rFailover, nodeName, masterPodName)
	} else {
		r1 = ret.Get(1).(resource.Quantity)
	}

	if rf, ok := ret.Get(2).(func(*v1.RedisFailover, string, string) error); ok {
		r2 = rf(rFailover, nodeName, masterPodName)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

func (_m *RedisFailoverCheck) GetStatefulSetResizeOnly(rFailover *v1.RedisFailover) (bool, error) {
	ret := _m.Called(rFailover)

	if len(ret) == 0 {
		panic("no return value specified for GetStatefulSetResizeOnly")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover) (bool, error)); ok {
		return rf(rFailover)
	}
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover) bool); ok {
		r0 = rf(rFailover)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(*v1.RedisFailover) error); ok {
		r1 = rf(rFailover)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *RedisFailoverCheck) GetPodNode(podName string, rFailover *v1.RedisFailover) (string, error) {
	ret := _m.Called(podName, rFailover)

	if len(ret) == 0 {
		panic("no return value specified for GetPodNode")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *v1.RedisFailover) (string, error)); ok {
		return rf(podName, rFailover)
	}
	if rf, ok := ret.Get(0).(func(string, *v1.RedisFailover) string); ok {
		r0 = rf(podName, rFailover)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, *v1.RedisFailover) error); ok {
		r1 = rf(podName, rFailover)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *RedisFailoverCheck) GetPodResizeCondition(podName string, rFailover *v1.RedisFailover) (bool, string, error) {
	ret := _m.Called(podName, rFailover)

	if len(ret) == 0 {
		panic("no return value specified for GetPodResizeCondition")
	}

	var r0 bool
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string, *v1.RedisFailover) (bool, string, error)); ok {
		return rf(podName, rFailover)
	}
	if rf, ok := ret.Get(0).(func(string, *v1.RedisFailover) bool); ok {
		r0 = rf(podName, rFailover)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, *v1.RedisFailover) string); ok {
		r1 = rf(podName, rFailover)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string, *v1.RedisFailover) error); ok {
		r2 = rf(podName, rFailover)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

func (_m *RedisFailoverCheck) GetResizeState(podName string, rFailover *v1.RedisFailover) (time.Time, string, bool, error) {
	ret := _m.Called(podName, rFailover)

	if len(ret) == 0 {
		panic("no return value specified for GetResizeState")
	}

	var r0 time.Time
	var r1 string
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(string, *v1.RedisFailover) (time.Time, string, bool, error)); ok {
		return rf(podName, rFailover)
	}
	if rf, ok := ret.Get(0).(func(string, *v1.RedisFailover) time.Time); ok {
		r0 = rf(podName, rFailover)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	if rf, ok := ret.Get(1).(func(string, *v1.RedisFailover) string); ok {
		r1 = rf(podName, rFailover)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string, *v1.RedisFailover) bool); ok {
		r2 = rf(podName, rFailover)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(string, *v1.RedisFailover) error); ok {
		r3 = rf(podName, rFailover)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

func (_m *RedisFailoverCheck) PodResourcesMatchDesired(podName string, rFailover *v1.RedisFailover) (bool, error) {
	ret := _m.Called(podName, rFailover)

	if len(ret) == 0 {
		panic("no return value specified for PodResourcesMatchDesired")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *v1.RedisFailover) (bool, error)); ok {
		return rf(podName, rFailover)
	}
	if rf, ok := ret.Get(0).(func(string, *v1.RedisFailover) bool); ok {
		r0 = rf(podName, rFailover)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, *v1.RedisFailover) error); ok {
		r1 = rf(podName, rFailover)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *RedisFailoverCheck) GetMaxRedisPodTime(rFailover *v1.RedisFailover) (time.Duration, error) {
	ret := _m.Called(rFailover)

	if len(ret) == 0 {
		panic("no return value specified for GetMaxRedisPodTime")
	}

	var r0 time.Duration
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover) (time.Duration, error)); ok {
		return rf(rFailover)
	}
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover) time.Duration); ok {
		r0 = rf(rFailover)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	if rf, ok := ret.Get(1).(func(*v1.RedisFailover) error); ok {
		r1 = rf(rFailover)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNumberMasters provides a mock function with given fields: rFailover
func (_m *RedisFailoverCheck) GetNumberMasters(rFailover *v1.RedisFailover) (int, error) {
	ret := _m.Called(rFailover)

	if len(ret) == 0 {
		panic("no return value specified for GetNumberMasters")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover) (int, error)); ok {
		return rf(rFailover)
	}
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover) int); ok {
		r0 = rf(rFailover)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(*v1.RedisFailover) error); ok {
		r1 = rf(rFailover)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRedisRevisionHash provides a mock function with given fields: podName, rFailover
func (_m *RedisFailoverCheck) GetRedisRevisionHash(podName string, rFailover *v1.RedisFailover) (string, error) {
	ret := _m.Called(podName, rFailover)

	if len(ret) == 0 {
		panic("no return value specified for GetRedisRevisionHash")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *v1.RedisFailover) (string, error)); ok {
		return rf(podName, rFailover)
	}
	if rf, ok := ret.Get(0).(func(string, *v1.RedisFailover) string); ok {
		r0 = rf(podName, rFailover)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, *v1.RedisFailover) error); ok {
		r1 = rf(podName, rFailover)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRedisesIPs provides a mock function with given fields: rFailover
func (_m *RedisFailoverCheck) GetRedisesIPs(rFailover *v1.RedisFailover) ([]string, error) {
	ret := _m.Called(rFailover)

	if len(ret) == 0 {
		panic("no return value specified for GetRedisesIPs")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover) ([]string, error)); ok {
		return rf(rFailover)
	}
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover) []string); ok {
		r0 = rf(rFailover)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(*v1.RedisFailover) error); ok {
		r1 = rf(rFailover)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRedisesMasterPod provides a mock function with given fields: rFailover
func (_m *RedisFailoverCheck) GetRedisesMasterPod(rFailover *v1.RedisFailover) (string, error) {
	ret := _m.Called(rFailover)

	if len(ret) == 0 {
		panic("no return value specified for GetRedisesMasterPod")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover) (string, error)); ok {
		return rf(rFailover)
	}
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover) string); ok {
		r0 = rf(rFailover)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*v1.RedisFailover) error); ok {
		r1 = rf(rFailover)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRedisesSlavesPods provides a mock function with given fields: rFailover
func (_m *RedisFailoverCheck) GetRedisesSlavesPods(rFailover *v1.RedisFailover) ([]string, error) {
	ret := _m.Called(rFailover)

	if len(ret) == 0 {
		panic("no return value specified for GetRedisesSlavesPods")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover) ([]string, error)); ok {
		return rf(rFailover)
	}
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover) []string); ok {
		r0 = rf(rFailover)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(*v1.RedisFailover) error); ok {
		r1 = rf(rFailover)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSentinelsIPs provides a mock function with given fields: rFailover
func (_m *RedisFailoverCheck) GetSentinelsIPs(rFailover *v1.RedisFailover) ([]string, error) {
	ret := _m.Called(rFailover)

	if len(ret) == 0 {
		panic("no return value specified for GetSentinelsIPs")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover) ([]string, error)); ok {
		return rf(rFailover)
	}
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover) []string); ok {
		r0 = rf(rFailover)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(*v1.RedisFailover) error); ok {
		r1 = rf(rFailover)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStatefulSetUpdateRevision provides a mock function with given fields: rFailover
func (_m *RedisFailoverCheck) GetStatefulSetUpdateRevision(rFailover *v1.RedisFailover) (string, error) {
	ret := _m.Called(rFailover)

	if len(ret) == 0 {
		panic("no return value specified for GetStatefulSetUpdateRevision")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover) (string, error)); ok {
		return rf(rFailover)
	}
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover) string); ok {
		r0 = rf(rFailover)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*v1.RedisFailover) error); ok {
		r1 = rf(rFailover)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsClusterRunning provides a mock function with given fields: rFailover
func (_m *RedisFailoverCheck) IsClusterRunning(rFailover *v1.RedisFailover) bool {
	ret := _m.Called(rFailover)

	if len(ret) == 0 {
		panic("no return value specified for IsClusterRunning")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover) bool); ok {
		r0 = rf(rFailover)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// IsRedisRunning provides a mock function with given fields: rFailover
func (_m *RedisFailoverCheck) IsRedisRunning(rFailover *v1.RedisFailover) bool {
	ret := _m.Called(rFailover)

	if len(ret) == 0 {
		panic("no return value specified for IsRedisRunning")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover) bool); ok {
		r0 = rf(rFailover)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// IsSentinelRunning provides a mock function with given fields: rFailover
func (_m *RedisFailoverCheck) IsSentinelRunning(rFailover *v1.RedisFailover) bool {
	ret := _m.Called(rFailover)

	if len(ret) == 0 {
		panic("no return value specified for IsSentinelRunning")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover) bool); ok {
		r0 = rf(rFailover)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewRedisFailoverCheck creates a new instance of RedisFailoverCheck. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRedisFailoverCheck(t interface {
	mock.TestingT
	Cleanup(func())
}) *RedisFailoverCheck {
	mock := &RedisFailoverCheck{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
