name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4 
        with:
          version: v3.12.3

      - name: Release
        uses: helm/chart-releaser-action@v1.5.0
        id: cr
        with:
          charts_dir: charts
          config: charts/chart-release-config.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      # setup access to container registry
      - name: Setup access to container registry
        uses: docker/login-action@v3
        if: ${{ steps.cr.outputs.changed_charts }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # push charts to container registry
      - name: Push charts to container registry
        if: ${{ steps.cr.outputs.changed_charts }}
        run: |
          for CHART in .cr-release-packages/*; do
            if [ -z "${CHART:-}" ]; then break; fi
            helm push "${CHART}" oci://ghcr.io/${{ github.repository_owner }}/charts
          done
